### ISSUE TITLE
Translation limited by screen border

### ISSUE THREAD

**Issue by Tarried** [ManlyMarco/StudioExtraMoveAxis#2]
It's basically impossible to move anything down, right, or forwards with any great degree, because the mouse immediately hits the screen border. 

Can you make it such that the translation continues to respect the mouse movement even at the screen border? 
e.g. much like how clicking the XYZ letters in the movement panel works.

**Comment by ManlyMarco** [comment]
Are you playing in fullscreen?

**Comment by Tarried** [comment]
Yes, but this issue still occurs in windowed mode. It feels like it's usable if you played in windowed, with a big display, and the game in the top left.

Also, like the other issue said, XY/XZ/YZ translation handles don't do what they're supposed to.

**Comment by ManlyMarco** [comment]
Fixed in #3

**Comment by Tarried** [comment]
Appreciate the quick response!
